[package]
name = "hotstuff2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blst = "0.3.11"
bit-vec = "0.6.3"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc", "atomic", "serde"] }
anyhow = "1.0"
rand = "0.8.0"
parking_lot = "0.12.1"